webtalk_init -webtalk_dir E:/test/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/breath_ip_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb  7 17:15:17 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "34907178-b8a7-4200-9244-6fcd1f5094a8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "86ff1e1611054299bd09a094087c3867" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "400 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "11.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14096_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1856039332 -regid "" -xml E:/test/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/breath_ip_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/test/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/breath_ip_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/test/project_4/project_4.sim/sim_1/behav/xsim/xsim.dir/breath_ip_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
